package com.docuhyphen.app.api.model.entity

enum class SecurityIncidentType
{
    AUTH_RATE_LIMIT_LOOKUP,
    AUTH_LOOKUP_SUSPICIOUS_PATTERN,
    AUTH_RATE_LIMIT_SIGNIN_INITIATE,
    AUTH_RATE_LIMIT_SIGNIN_COMPLETION,
    AUTH_RATE_LIMIT_OAUTH_AUTHORIZE,
    AUTH_RATE_LIMIT_OAUTH_CALLBACK,
    AUTH_RATE_LIMIT_REFRESH,
    AUTH_RATE_LIMIT_DIRECTORY_LOOKUP,
    AUTH_RATE_LIMIT_EXTERNAL_IDENTITY_RESOLUTION,
    CSRF_VALIDATION_FAILURE,
    OAUTH_CALLBACK_INVALID_REQUEST,
    OAUTH_STATE_VALIDATION_FAILURE,
    OAUTH_STATE_REPLAY_OR_INVALID,
    REFRESH_TOKEN_REUSE_DETECTED,
    ORG_IDP_SECRET_ROTATION_FAILURE,
    ORG_IDP_SECRET_RUNTIME_POLICY_DENY,
}





