package com.docuhyphen.app.api.exception

class EmailNotFoundException() : Exception("Email not found")
class InvalidOtpException(message: String? = "Invalid otp") : RuntimeException(message)
class OtpRequiredException() : RuntimeException("Verification code is required")
class PasswordMismatchException() : RuntimeException("Passwords do not match")
class PasswordContainsEmailException() : RuntimeException("Passwords cannot contain email")
class MaxAttemptsOTPExceededException(minutesTillNextAttempt: String) : RuntimeException(minutesTillNextAttempt)
class OTPExpiredException(otp: String) : RuntimeException(otp)
class InvalidEmailException(message: String = "Email is invalid") : RuntimeException(message)
class DisposableEmailAddressException() : RuntimeException("Disposable email addresses cannot be used to sign up")
class AppUserExistsException() : RuntimeException("An account with this email already exists")
class InvalidSignUpConfirmationTokenException(message: String = "This verification link is invalid or has expired.") : RuntimeException(message)
class SignUpVerificationRejectedException(message: String = SIGN_UP_VERIFICATION_REJECTED_MESSAGE) : RuntimeException(message)
class SignUpVerificationBusyException(message: String = SIGN_UP_VERIFICATION_REJECTED_MESSAGE) : RuntimeException(message)
const val SIGN_UP_VERIFICATION_REJECTED_MESSAGE = "The verification code is invalid or has expired. Check the code or request a new one."
class SignUpRateLimitedException(message: String = "Too many requests. Please try again later.") : RuntimeException(message)
class SignUpResendCooldownException(val retryAfterSeconds: Long) :
    RuntimeException("Please wait $retryAfterSeconds seconds before requesting another verification code.")
class EmailRequiredException() : RuntimeException("Email is required")
class PasswordRequiredException() : RuntimeException("Password is required")
class ConfirmationPasswordRequiredException() : RuntimeException("Confirmation password is required")
class PasswordRequirementsNotMetException() : RuntimeException("Password requirements not met")
class InvalidSignInCredentialsException(message: String? = "Email or password incorrect") : RuntimeException(message)
class InactiveAccountException(message: String = "This account is not currently active. If you were invited to an Exchange, please sign up first. If you believe this is an error, please contact the person who sent you the invitation.") : RuntimeException(message)
class SignUpRequiredException(message: String = "This email has not finished account setup yet. Sign up first to create your password and access the Exchange.") : RuntimeException(message)
class TemporaryPasswordExpiredException(message: String = "Your temporary password has expired. Please recover your password to continue.") : RuntimeException(message)
class PasswordChangeRequiredException(message: String = "You must change your temporary password before signing in. Please use account recovery.") : RuntimeException(message)
class DataIntegrityException(message: String) : RuntimeException(message)
class MaximumSignInAttemptsExceeded() : RuntimeException("Maximum sign in attempts exceeded. Your account will be locked")
class AuthTokenNotProvidedException() : RuntimeException("Token not provided")
class AuthTokenNotFoundException() : RuntimeException("Auth token not found")
class AuthTokenExpiredException() : RuntimeException("Auth token expired")
class AuthTokenInvalidException() : RuntimeException("Auth token invalid")
class InvalidPersonRegistrationException(message: String?) : RuntimeException(message)
class InvalidOrganizationRegistrationException(message: String?) : RuntimeException(message)
class PersonAlreadyExistsException() : RuntimeException("Person already exists")
class OrganizationAlreadyExistsException() : RuntimeException("Organization already exists")
class OrganizationNotFoundException(message: String?) : RuntimeException(message)
class OrganizationGroupNotFoundException(message: String?) : RuntimeException(message)
class AppUserNotFoundException(message: String?) : RuntimeException(message)
class ExchangeNotFoundException(message: String?) : RuntimeException(message)
class ExchangeDocumentNotFoundException(message: String?) : RuntimeException(message)
class TooManyRequestsException(message: String?) : RuntimeException(message)
class LastAppAdminException(message: String = "Cannot remove the last application administrator") : RuntimeException(message)
class RoleScopeViolationException(message: String) : RuntimeException(message)
class ApplicationNotFoundException(message: String? = "Application not found") : RuntimeException(message)
