package com.docuhyphen.app.api.exception

import SignUpStatus

class EmailNotFoundException() : Exception("Email not found")
class InvalidOtpException(message: String? = "Invalid otp") : RuntimeException(message)
class OtpRequiredException() : RuntimeException("Otp is required")
class PasswordMismatchException() : RuntimeException("Passwords do not match")
class PasswordContainsEmailException() : RuntimeException("Passwords cannot contain email")
class MaxAttemptsOTPExceededException(minutesTillNextAttempt: String) : RuntimeException(minutesTillNextAttempt)
class OtpMaxRetryLimitReachedException(message: String) : RuntimeException(message)
class IncorrectSignUpCompletionStatusException(status: SignUpStatus) : RuntimeException("Incorrect sign up completion status $status")
class OTPExpiredException(otp: String) : RuntimeException(otp)
class OtpRegenerationCooldownException(message: String = "Please wait before requesting a new OTP.") : RuntimeException(message)
class InvalidSignUpStatusException(message: String) : RuntimeException(message)
class InvalidEmailException(message: String = "Email is invalid") : RuntimeException("")
class EmailExistsException() : RuntimeException("Email already exists")
class AppUserExistsException() : RuntimeException("An account with this email already exists")
class ExistingSignUpException() : RuntimeException("It seems you've already initiated the sign-up process. Please check your email for the OTP to continue")
class EmailRequiredException() : RuntimeException("Email is required")
class PasswordRequiredException() : RuntimeException("Password is required")
class ConfirmationPasswordRequiredException() : RuntimeException("Confirmation password is required")
class PasswordRequirementsNotMetException() : RuntimeException("Password requirements not met")
class InvalidSignInCredentialsException(message: String? = "Email or password incorrect") : RuntimeException(message)
class DataIntegrityException(message: String) : RuntimeException(message)
class MaximumSignInAttemptsExceeded() : RuntimeException("Maximum sign in attempts exceeded. Your account will be locked")
class AuthTokenNotProvidedException() : RuntimeException("Token not provided")
class AuthTokenNotFoundException() : RuntimeException("Auth token not found")
class AuthTokenExpiredException() : RuntimeException("Auth token expired")
class AuthTokenInvalidException() : RuntimeException("Auth token invalid")
class InvalidPersonRegistrationException(message: String?) : RuntimeException(message)
class InvalidOrganizationRegistrationException(message: String?) : RuntimeException(message)
class PersonAlreadyExistsException() : RuntimeException("Person already exists")
class OrganizationAlreadyExistsException() : RuntimeException("Organization already exists")
class OrganizationNotFoundException(message: String?) : RuntimeException(message)
class OrganizationLinkNotFoundException(message: String? = "") : RuntimeException(message)
class OrganizationGroupNotFoundException(message: String?) : RuntimeException(message)
class AppUserNotFoundException(message: String?) : RuntimeException(message)
class SharingSessionNotFoundException(message: String?) : RuntimeException(message)
class SharingSessionDocumentNotFoundException(message: String?) : RuntimeException(message)
class TooManyRequestsException(message: String?) : RuntimeException(message)
