import {makeStyles, tokens} from "@fluentui/react-components";

export const useAccountRecoveryStyles = makeStyles({
    signUpCompletionForm: {
        display: "flex",
        flexDirection: "column",
        gap: "4px",
    },
    authHasAccount: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: "8px",
    },
    passwordResetSuccessfulSection: {
        display: "flex",
        flex: 1,
        flexDirection: "column",
        gap: "20px",
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
    },
    passwordResetSuccessfulFullscreen: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: "20px",
        textAlign: "center",
        width: "100%",
        height: "100%",
        minHeight: "100vh",
        padding: "32px",
        boxSizing: "border-box",
        background: tokens.colorNeutralBackground2,
    },
    passwordResetSuccessfulCard: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: "20px",
        textAlign: "center",
        maxWidth: "480px",
        width: "100%",
        padding: "40px",
        borderRadius: "16px",
        background: tokens.colorNeutralBackground1,
        boxShadow: tokens.shadow16,
    },
});