import {makeStyles, tokens} from "@fluentui/react-components";

export const useAccountRecoveryStyles = makeStyles({
    signUpCompletionForm: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingHorizontalXS,
    },
    authHasAccount: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
    },
    passwordResetSuccessfulSection: {
        display: "flex",
        flex: 1,
        flexDirection: "column",
        gap: tokens.spacingHorizontalXL,
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
    },
    passwordResetSuccessfulFullscreen: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: tokens.spacingHorizontalXL,
        textAlign: "center",
        width: "100%",
        height: "100%",
        minHeight: "100vh",
        padding: tokens.spacingHorizontalXXXL,
        boxSizing: "border-box",
        background: tokens.colorNeutralBackground2,
    },
    passwordResetSuccessfulCard: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: tokens.spacingHorizontalXL,
        textAlign: "center",
        maxWidth: "480px",
        width: "100%",
        padding: tokens.spacingHorizontalXXXL,
        borderRadius: tokens.borderRadiusXLarge,
        background: tokens.colorNeutralBackground1,
        boxShadow: tokens.shadow16,
    },
});