version: '3.8'

services:
  quarkus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docu-hyphen-app
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./document-uploads:/app/document-uploads
      - ./logs:/app/logs
    environment:
      QUARKUS_HTTP_HOST: 0.0.0.0
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:15
    container_name: docu-hyphen-postgres-db
    environment:
      POSTGRES_DB: docu-hyphen-postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: doc-hyphen-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres-data:
  redis-data:
