package com.securedocsshare.app.api.model

class EmailNotFoundException() : Exception("Email not found")
class InvalidOtpException() : RuntimeException("Invalid otp")
class OtpRequiredException() : RuntimeException("Otp is required")
class PasswordMismatchException() : RuntimeException("Passwords do not match")
class PasswordContainsEmailException() : RuntimeException("Passwords cannot contain email")
class MaxAttemptsOTPExceededException(minutesTillNextAttempt: String) : RuntimeException(minutesTillNextAttempt)
class IncorrectSignUpCompletionStatusException(status: SignUpStatus) : RuntimeException("Incorrect sign up completion status $status")
class OTPExpiredException(otp: String) : RuntimeException("OTP $otp expired ")
class InvalidSignUpStatusException(message: String) : RuntimeException(message)
class InvalidEmailException() : RuntimeException("Email is invalid")
class EmailExistsException() : RuntimeException("Email already exists")
class AppUserExistsException() : RuntimeException("An account with this email already exists. Please sign in.")
class ExistingSignUpException() : RuntimeException("It seems you've already initiated the sign-up process. Please check your email for the OTP to continue")
class EmailRequiredException() : RuntimeException("Email is required")
class PasswordRequiredException() : RuntimeException("Password is required")
class ConfirmationPasswordRequiredException() : RuntimeException("Confirmation password is required")
class PasswordRequirementsNotMetException() : RuntimeException("Password requirements not met")
class InvalidSignInCredentialsException() : RuntimeException("Username or password incorrect")
class DataIntegrityException(message: String) : RuntimeException(message)
class MaximumSignInAttemptsExceeded() : RuntimeException("Maximum sign in attempts exceeded. Your account will be locked")
class AuthTokenNotProvidedException() : RuntimeException("Token not provided")
class AuthTokenNotFoundException() : RuntimeException("Auth token not found")
class AuthTokenExpiredException() : RuntimeException("Auth token expired")
class AuthTokenInvalidException() : RuntimeException("Auth token invalid")
class InvalidPersonRegistrationException(message: String?) : RuntimeException(message)
class InvalidCompanyRegistrationException(message: String?) : RuntimeException(message)
class PersonAlreadyExistsException() : RuntimeException("Person already exists")
class CompanyAlreadyExistsException() : RuntimeException("Company already exists")
