#quarkus.jaxrs.filter.classes=your.package.EndpointVerificationFilter

# Quarkus Mailer Configuration
quarkus.mailer.from=admin@securedocumentshare.co.za
quarkus.mailer.host=localhost
quarkus.mailer.port=32768
quarkus.mailer.username=admin@securedocumentshare.co.za
quarkus.mailer.password=admin
quarkus.mailer.ssl=false

#Logging
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n
quarkus.log.file.enable=true
quarkus.log.file.path=logs/application.log
quarkus.log.file.level=DEBUG

# Hibernate ORM configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/secure_document_share
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
