import {makeStyles, tokens} from '@fluentui/react-components';

export const useExchangeFieldsTabStyles = makeStyles({
    container: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        height: '100%',
        minHeight: 0,
        boxSizing: 'border-box',
        overflow: 'hidden',
        padding: '8px 4px 20px',
    },
    headerRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: '16px',
        flexWrap: 'wrap',
    },
    headerTitleBlock: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        minWidth: 0,
    },
    sectionEyebrow: {
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase200,
        textTransform: 'uppercase',
        letterSpacing: '0.04em',
    },
    schemaTitle: {
        fontSize: tokens.fontSizeBase500,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    schemaSummaryCard: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: '16px',
        flexWrap: 'wrap',
        padding: '18px 20px',
        borderRadius: tokens.borderRadiusXLarge,
        backgroundColor: tokens.colorNeutralBackground2,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    headerDescription: {
        color: tokens.colorNeutralForeground2,
        maxWidth: '720px',
        lineHeight: tokens.lineHeightBase300,
    },
    subText: {
        color: tokens.colorNeutralForeground3,
    },
    errorText: {
        color: tokens.colorPaletteRedForeground1,
    },
    emptyState: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        alignItems: 'flex-start',
        padding: '12px 0',
    },
    assignRow: {
        display: 'flex',
        gap: '8px',
        alignItems: 'flex-end',
        flexWrap: 'wrap',
    },
    grow: {
        flex: '1',
        minWidth: '220px',
    },
    fieldList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    fieldForm: {
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
        minHeight: 0,
    },
    scrollableFieldSections: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        flex: 1,
        minHeight: 0,
        overflowY: 'auto',
        overflowX: 'hidden',
        scrollbarGutter: 'stable',
        paddingRight: '4px',
        paddingBottom: '16px',
    },
    sectionBlock: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    sectionHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '12px',
        flexWrap: 'wrap',
    },
    sectionTitle: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    fieldLane: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 300px), 1fr))',
        gap: '16px',
    },
    fieldCardItem: {
        minWidth: 0,
        width: '100%',
    },
    fieldCard: {
        display: 'flex',
        flexDirection: 'column',
        gap: '14px',
        height: '100%',
        minWidth: 0,
        boxSizing: 'border-box',
        padding: '16px',
        borderRadius: tokens.borderRadiusLarge,
        backgroundColor: tokens.colorNeutralBackground1,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
    },
    fieldCardHeader: {
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: '12px',
        flexWrap: 'wrap',
    },
    fieldCardTitleBlock: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        minWidth: 0,
        flex: 1,
    },
    fieldCardMeta: {
        display: 'flex',
        gap: '8px',
        flexWrap: 'wrap',
        alignItems: 'center',
    },
    fieldLabelRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        minWidth: 0,
    },
    fieldLabel: {
        fontSize: tokens.fontSizeBase300,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground1,
    },
    fieldValueArea: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        minWidth: 0,
    },
    label: {
        fontWeight: tokens.fontWeightSemibold,
    },
    fieldValueText: {
        fontSize: tokens.fontSizeBase400,
        lineHeight: tokens.lineHeightBase400,
        color: tokens.colorNeutralForeground1,
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-word',
    },
    fieldValuePlaceholder: {
        color: tokens.colorNeutralForeground3,
        fontStyle: 'italic',
    },
    valueBadgeRow: {
        display: 'flex',
        gap: '8px',
        flexWrap: 'wrap',
    },
    editorField: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    buttonRow: {
        display: 'flex',
        gap: '8px',
        justifyContent: 'flex-end',
        flexWrap: 'wrap',
        flexShrink: 0,
        paddingTop: '12px',
    },
    schemaBadgeRow: {
        display: 'flex',
        gap: '8px',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
});
