package com.docuhyphen.app.api.service.auth

enum class RevocationReasonCode
{
    LOGOUT_DEVICE,
    LOGOUT_ALL_DEVICES,
    PASSWORD_CHANGED,
    ADMIN_REVOKE,
    DEPROVISIONED,
    ORG_INACTIVE,
    MEMBERSHIP_INACTIVE,
    SESSION_VERSION_MISMATCH,
    REFRESH_REUSE_DETECTED,
    REFRESH_INVALID,
    REFRESH_ROTATED,
    SESSION_EXPIRED,
    RATE_LIMIT,
    STEP_UP_REQUIRED,
    RISK_SIGNAL_DETECTED,
    CSRF_VALIDATION_FAILED,
    OIDC_VALIDATION_FAILED,
    ORG_IDP_SECRET_DISABLED,
    ORG_IDP_SECRET_RETIRE_PENDING,
    ORG_IDP_SECRET_RUNTIME_PHASE_DENY,
    SECURITY_POLICY,
    SYSTEM_MAINTENANCE,
}





