import {makeStyles, shorthands, tokens} from "@fluentui/react-components";

export const useExchangeDocumentVersionsStyles = makeStyles({
    container: {
        display: "flex",
        flexDirection: "column",
        height: "100%",
        gap: tokens.spacingVerticalM,
    },
    versionList: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
        overflowY: "auto",
        flexGrow: 1,
        minHeight: 0,
    },
    uploadButtonRow: {
        display: "flex",
        justifyContent: "flex-end",
        alignItems: "center",
        ...shorthands.padding(tokens.spacingVerticalS, 0),
        borderTop: `1px solid ${tokens.colorNeutralStroke1}`,
        flexShrink: 0,
    },
    versionCard: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXS,
        ...shorthands.padding(tokens.spacingVerticalS, tokens.spacingHorizontalM),
        ...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
        ...shorthands.borderRadius(tokens.borderRadiusMedium),
        backgroundColor: tokens.colorNeutralBackground1,
    },
    versionCardHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
    },
    versionCardActions: {
        display: "flex",
        gap: tokens.spacingHorizontalXS,
        alignItems: "center",
    },
    versionCardMeta: {
        display: "flex",
        gap: tokens.spacingHorizontalM,
        color: tokens.colorNeutralForeground3,
    },
    versionFileName: {
        color: tokens.colorNeutralForeground3,
        ...shorthands.overflow("hidden"),
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    noVersions: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "200px",
        ...shorthands.gap(tokens.spacingVerticalL),
        color: tokens.colorNeutralForeground3,
    },
    previewDialogSurface: {
        width: "90vw",
        maxWidth: "1100px",
        height: "90vh",
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        margin: "auto",
        ...shorthands.padding(0),
    },
    previewCloseButton: {
        position: "absolute",
        top: "8px",
        right: "8px",
        zIndex: 10,
    },
    previewDialogBody: {
        display: "flex",
        flexDirection: "column",
        height: "100%",
        ...shorthands.padding(0),
    },
    previewDialogContent: {
        flexGrow: 1,
        display: "flex",
        flexDirection: "column",
        ...shorthands.padding(0),
        overflow: "hidden",
    },
    previewIframe: {
        width: "100%",
        flexGrow: 1,
        border: "none",
        minHeight: "0",
        height: "100%",
    },
    errorText: {
        color: tokens.colorStatusDangerForeground1,
    },
});