import {makeStyles, tokens} from '@fluentui/react-components';

export const useFieldsTabStyles = makeStyles({
    container: {
        display: 'flex',
        flexDirection: 'column',
        gap: "0",
        height: '100%',
        minHeight: 0,
    },
    stickyBlock: {
        background: tokens.colorNeutralBackground1,
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalS,
        paddingBottom: tokens.spacingVerticalM,
        flexShrink: 0,
        paddingInline: tokens.spacingHorizontalS,
        boxSizing: 'border-box',
    },
    scrollableContent: {
        flex: 1,
        minHeight: 0,
        overflowY: 'auto',
        overflowX: 'hidden',
        overscrollBehavior: 'contain',
        paddingInline: tokens.spacingHorizontalS,
        boxSizing: 'border-box',
    },
    tabsHeaderRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: tokens.spacingHorizontalS,
    },
    headerRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
        flexWrap: 'wrap',
    },
    searchRow: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
        width: '100%',
        '@media screen and (max-width: 600px)': {
            alignItems: 'stretch',
            flexDirection: 'column',
        },
    },
    searchRowInputs: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingVerticalS,
        flex: '0 1 auto',
        minWidth: 0,
        '@media screen and (max-width: 600px)': {
            width: '100%',
        },
    },
    searchField: {
        flex: '0 1 420px',
        minWidth: 0,
        width: '420px',
        maxWidth: '100%',
        '@media screen and (max-width: 600px)': {
            flex: 1,
            width: 'auto',
        },
    },
    descriptionText: {
        color: tokens.colorNeutralForeground3,
    },
    errorText: {
        color: tokens.colorPaletteRedForeground1,
    },
    emptyText: {
        color: tokens.colorNeutralForeground3,
    },
    list: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalS,
    },
    cardGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: tokens.spacingHorizontalM,
        '@media screen and (max-width: 768px)': {
            gridTemplateColumns: '1fr',
        },
    },
    card: {
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        borderRadius: tokens.borderRadiusXLarge,
        padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalL}`,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'stretch',
        gap: tokens.spacingHorizontalS,
    },
    cardMain: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalXS,
        minWidth: '0',
        flex: '1',
    },
    cardFieldName: {
        fontWeight: tokens.fontWeightSemibold,
        fontSize: tokens.fontSizeBase300,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    cardFieldKey: {
        fontFamily: 'monospace',
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    cardCol2: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        justifyContent: 'center',
        flexShrink: 0,
        gap: tokens.spacingHorizontalXS,
    },
    schemaCardCol2: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        flexShrink: 0,
        gap: tokens.spacingHorizontalXS,
    },
    cardTitleRow: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
        flexWrap: 'wrap',
    },
    codeKey: {
        fontFamily: 'monospace',
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
    },
    subText: {
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase200,
        overflow: 'hidden',
        display: '-webkit-box',
        WebkitLineClamp: '2',
        WebkitBoxOrient: 'vertical',
    },
    actionGroup: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalXS,
        flexShrink: 0,
    },
    badgeRow: {
        display: 'flex',
        gap: tokens.spacingHorizontalSNudge,
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    drawerBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalL,
        paddingTop: tokens.spacingVerticalL,
    },
    fieldGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalM,
    },
    twoColumn: {
        display: 'flex',
        gap: tokens.spacingHorizontalM,
        flexWrap: 'wrap',
    },
    grow: {
        flex: '1',
        minWidth: '160px',
    },
    optionRow: {
        display: 'flex',
        gap: tokens.spacingHorizontalS,
        alignItems: 'flex-end',
    },
    bindingRow: {
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: tokens.borderRadiusMedium,
        padding: `${tokens.spacingVerticalMNudge} ${tokens.spacingHorizontalM}`,
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalS,
    },
    bindingHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
    },
    bindingToggles: {
        display: 'flex',
        gap: tokens.spacingHorizontalL,
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    buttonRow: {
        display: 'flex',
        gap: tokens.spacingHorizontalS,
        justifyContent: 'flex-end',
        flexWrap: 'wrap',
    },
    inlineSpinner: {
        paddingTop: tokens.spacingVerticalS,
    },
    filterPopover: {
        padding: tokens.spacingHorizontalS,
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalS,
        minWidth: '200px',
        maxWidth: '280px',
    },
    filterSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingHorizontalXS,
    },
    filterSectionTitle: {
        fontSize: tokens.fontSizeBase200,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground3,
        paddingLeft: tokens.spacingHorizontalXXS,
    },
    filterSectionList: {
        maxHeight: '160px',
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
    },
    filterDivider: {
        border: 'none',
        borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
        margin: "0",
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    th: {
        textAlign: 'left',
        padding: `${tokens.spacingVerticalSNudge} ${tokens.spacingHorizontalM}`,
        fontSize: tokens.fontSizeBase200,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground3,
        borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
        whiteSpace: 'nowrap',
    },
    tr: {
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        ':hover': {
            backgroundColor: tokens.colorNeutralBackground2,
        },
    },
    td: {
        padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
        verticalAlign: 'middle',
    },
    dialogTitle: {
        display: 'flex',
        justifyContent: "space-between"
    },
});
