import {makeStyles, tokens} from '@fluentui/react-components';

export const useFieldsTabStyles = makeStyles({
    container: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0',
        padding: '0 4px',
    },
    stickyBlock: {
        position: 'sticky',
        top: 0,
        zIndex: 1,
        background: tokens.colorNeutralBackground1,
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        paddingBottom: '12px',
    },
    tabsHeaderRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: '8px',
    },
    headerRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '8px',
        flexWrap: 'wrap',
    },
    searchRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        width: '100%',
    },
    descriptionText: {
        color: tokens.colorNeutralForeground3,
    },
    errorText: {
        color: tokens.colorPaletteRedForeground1,
    },
    emptyText: {
        color: tokens.colorNeutralForeground3,
    },
    list: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    cardGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: '12px',
        '@media screen and (max-width: 768px)': {
            gridTemplateColumns: '1fr',
        },
    },
    card: {
        border: `1px solid ${tokens.colorNeutralStroke1}`,
        borderRadius: tokens.borderRadiusXLarge,
        padding: '12px 16px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'stretch',
        gap: '8px',
    },
    cardMain: {
        display: 'flex',
        flexDirection: 'column',
        gap: '3px',
        minWidth: '0',
        flex: '1',
    },
    cardFieldName: {
        fontWeight: tokens.fontWeightSemibold,
        fontSize: tokens.fontSizeBase300,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    cardFieldKey: {
        fontFamily: 'monospace',
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
    },
    cardFieldType: {
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
    },
    cardCol2: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        justifyContent: 'center',
        flexShrink: 0,
        gap: '4px',
    },
    schemaCardCol2: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        flexShrink: 0,
        gap: '4px',
    },
    cardTitleRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        flexWrap: 'wrap',
    },
    codeKey: {
        fontFamily: 'monospace',
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
    },
    subText: {
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase200,
        overflow: 'hidden',
        display: '-webkit-box',
        WebkitLineClamp: '2',
        WebkitBoxOrient: 'vertical',
    },
    actionGroup: {
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        flexShrink: 0,
    },
    badgeRow: {
        display: 'flex',
        gap: '6px',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    drawerBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        paddingTop: '16px',
    },
    fieldGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    twoColumn: {
        display: 'flex',
        gap: '12px',
        flexWrap: 'wrap',
    },
    grow: {
        flex: '1',
        minWidth: '160px',
    },
    optionRow: {
        display: 'flex',
        gap: '8px',
        alignItems: 'flex-end',
    },
    bindingRow: {
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        borderRadius: tokens.borderRadiusMedium,
        padding: '10px 12px',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    bindingHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '8px',
    },
    bindingToggles: {
        display: 'flex',
        gap: '16px',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    buttonRow: {
        display: 'flex',
        gap: '8px',
        justifyContent: 'flex-end',
        flexWrap: 'wrap',
    },
    inlineSpinner: {
        paddingTop: '8px',
    },
    filterPopover: {
        padding: '8px',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        minWidth: '200px',
        maxWidth: '280px',
    },
    filterSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    filterSectionTitle: {
        fontSize: tokens.fontSizeBase200,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground3,
        paddingLeft: '2px',
    },
    filterSectionList: {
        maxHeight: '160px',
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
    },
    filterDivider: {
        border: 'none',
        borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
        margin: '0',
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    th: {
        textAlign: 'left',
        padding: '6px 12px',
        fontSize: tokens.fontSizeBase200,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground3,
        borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
        whiteSpace: 'nowrap',
    },
    tr: {
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        ':hover': {
            backgroundColor: tokens.colorNeutralBackground2,
        },
    },
    td: {
        padding: '8px 12px',
        verticalAlign: 'middle',
    },
    dialogTitle: {
        display: 'flex',
        justifyContent: "space-between"
    },
});
