### Get current logged in user
GET {{host}}/app-user
Authorization: Bearer {{Authorization}}
Content-Type: application/json

### Get organization
GET {{host}}/app-user/{{appUserId}}/person/{{personId}}/organization
Authorization: Bearer {{Authorization}}
Content-Type: application/json

### Update Current User Settings
PUT {{host}}/app-user/settings
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "notifyLogin": false,
  "autoPreviewDocuments": false,
  "notifyShareStart": false,
  "notifyShareAccept": false,
  "notifyShareDecline": false,
  "notifyShareEnd": false,
  "notifyDocComment": false,
  "notifyDocDelete": false,
  "notifyDocAdd": false,
  "notifyDocUpload": true
}

### Update Specific User Settings
PUT {{host}}/app-user/3a377013-9eea-4c42-8ccc-032a1d7e8c9c/settings
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "notifyLogin": false,
  "autoPreviewDocuments": false,
  "notifyShareStart": false,
  "notifyShareAccept": false,
  "notifyShareDecline": true,
  "notifyShareEnd": false,
  "notifyDocComment": false,
  "notifyDocDelete": false,
  "notifyDocAdd": false,
  "notifyDocUpload": false
}

### Get current logged in user person
PUT {{host}}/app-user/person
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "firstName": "Stoic",
  "lastName": "Boi"
}