### Phone Number - Initiate Addition
POST http://localhost:8080/contact-details/{{contactDetailsId}}/phone/addition-initiation
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "phoneNumber": "+1234567860"
}

### Phone Number - Complete Addition
POST http://localhost:8080/contact-details/{{contactDetailsId}}/phone/addition-completion
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "phoneNumber": "+1234567860",
  "verificationCode": "167724"
}

### Phone Number - Initiate Update
POST http://localhost:8080/contact-details/{{contactDetailsId}}/phone/initiate-update
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "phoneNumber": "+9876543210"
}

### Phone Number - Complete Update
POST http://localhost:8080/contact-details/{{contactDetailsId}}/phone/complete-update
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "phoneNumber": "+9876543210",
  "verificationCode": "312980"
}

### Email - Initiate Addition
POST http://localhost:8080/contact-details/{{contactDetailsId}}/email/addition-initiation
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "email": "test@example.com"
}

### Email - Complete Addition
POST http://localhost:8080/contact-details/{{contactDetailsId}}/email/addition-completion
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "email": "test@example.com",
  "verificationCode": "123456"
}

### Email - Initiate Update
POST http://localhost:8080/contact-details/{{contactDetailsId}}/email/initiate-update
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "email": "updated@example.com"
}

### Email - Complete Update
POST http://localhost:8080/contact-details/{{contactDetailsId}}/email/complete-update
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "email": "updated@example.com",
  "verificationCode": "123456"
}