### Get organization
GET http://localhost:8080/app-user/d4f5484e-a246-4c33-9481-4f0cc88f7ff9/person/82da36b2-43bf-40dc-bb54-ff5f51fe702f/organization
Authorization: Bearer {{Authorization}}
Content-Type: application/json

### Update organization
PUT http://localhost:8080/organizations/{{organizationId}}
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "name": "The Test Organiz"
}

### Add organization group
POST http://localhost:8080/organizations/{{organizationId}}/groups
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "name": "Test Group2",
  "members": [
    {
      "appUserId": "d4f5484e-a246-4c33-9481-4f0cc88f7ff9",
      "allowSessionAccept": false,
      "allowSessionReject": true,
      "allowSessionEdit": false,
      "allowSessionDelete": false,
      "allowSessionEnd": true,
      "allowDocumentAddition": true,
      "allowDocumentDeletion": false,
      "allowDocumentDownload": true,
      "allowDocumentUpdate": true,
      "allowDocumentUpload": true
    }
  ]
}

### Update organization group
PUT http://localhost:8080/organizations/{{organizationId}}/groups/0262fab8-05ae-4493-9353-b3d27a51702d
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "name": "Test GroupEEE",
  "members": [
    {
      "appUserId": "d4f5484e-a246-4c33-9481-4f0cc88f7ff9",
      "allowSessionAccept": false,
      "allowSessionReject": true,
      "allowSessionEdit": false,
      "allowSessionDelete": false,
      "allowSessionEnd": true,
      "allowDocumentAddition": true,
      "allowDocumentDeletion": false,
      "allowDocumentDownload": true,
      "allowDocumentUpdate": true,
      "allowDocumentUpload": true
    }
  ]
}

### Get organization groups
GET http://localhost:8080/organizations/{{organizationId}}/groups
Authorization: Bearer {{Authorization}}
Content-Type: application/json

### DELETE organization group
DELETE http://localhost:8080/organizations/{{organizationId}}/groups/cedcaeb3-9e3d-43d2-9365-fd1fd031caea
Authorization: Bearer {{Authorization}}

### Add organization app user
POST http://localhost:8080/organizations/{{organizationId}}/app-users
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "role": "ORG_MEMBER",
  "email": "test4@doc-hyphen.com",
  "person": {
      "firstName": "John",
      "lastName": "Doe"
  }
}

### Get organization app users
GET http://localhost:8080/organizations/{{organizationId}}/app-users
Authorization: Bearer {{Authorization}}

### Deactivate organization app users
DELETE http://localhost:8080/organizations/{{organizationId}}/app-users/3a377013-9eea-4c42-8ccc-032a1d7e8c9c
Authorization: Bearer {{Authorization}}

### Update organization app user
PUT http://localhost:8080/organizations/{{organizationId}}/app-users/3a377013-9eea-4c42-8ccc-032a1d7e8c9c
Authorization: Bearer {{Authorization}}
Content-Type:  application/json

{
    "isActive": false,
    "email": "test5@doc-hyphen.com",
    "role": "ORG_ADMIN",
    "person": {
      "firstName": "CINTHIA",
      "lastName": "Doe"
    }
  }