### Get organization
GET http://localhost:8080/organizations/{{organizationId}}
Authorization: Bearer {{Authorization}}
Content-Type: application/json

### Add organization group
POST http://localhost:8080/organizations/{{organizationId}}/groups
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "name": "Test Group2",
  "members": [
    {
      "appUserId": "d4f5484e-a246-4c33-9481-4f0cc88f7ff9",
      "allowSessionAccept": true,
      "allowSessionReject": true,
      "allowSessionEdit": false,
      "allowSessionDelete": false,
      "allowSessionEnd": true,
      "allowDocumentAddition": true,
      "allowDocumentDeletion": false,
      "allowDocumentDownload": true,
      "allowDocumentUpdate": true,
      "allowDocumentUpload": true
    }
  ]
}

### Get organization groups
GET http://localhost:8080/organizations/{{organizationId}}/groups
Authorization: Bearer {{Authorization}}
Content-Type: application/json

### Delete organization groups
DELETE http://localhost:8080/organizations/{{organizationId}}/groups/0bee9833-23d7-42ee-a870-1fa174746559
Authorization: Bearer {{Authorization}}

### Add organization app user
POST http://localhost:8080/organizations/{{organizationId}}/app-users
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "role": "ORG_MEMBER",
  "email": "test4@doc-hyphen.com",
  "person": {
      "firstName": "John",
      "lastName": "Doe"
  }
}

### Get organization app users
GET http://localhost:8080/organizations/{{organizationId}}/app-users
Authorization: Bearer {{Authorization}}

### Deactivate organization app users
DELETE http://localhost:8080/organizations/{{organizationId}}/app-users/3c4098f3-a36c-4d9f-aa42-3ddf9dbc4126
Authorization: Bearer {{Authorization}}