### Initiate sharing session
POST http://localhost:8080/sharing-sessions
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "sessionName": "Pagination test 1",
  "description": "THe description",
  "recipientEmail": "test2@doc-hyphen.com",
  "initialShareMessage": "The start message",
  "sessionDocuments": [
    {
      "title": "Test document 1",
      "restrictType": false
    }
  ],
  "requestRecipientSignIn": false,
  "allowDocumentAddition": false,
  "allowDocumentDeletion": false,
  "allowDocumentDownload": false,
  "allowDocumentUpdate": false,
  "allowDocumentUpload": false
}

### Get logged in user sharing sessions
GET http://localhost:8080/sharing-sessions
Authorization: Bearer {{Authorization}}
Content-Type: application/json

### Get sharing session by id
GET http://localhost:8080/sharing-sessions/b4b502a5-86d0-4e59-ba05-f588a0acb9e6
Authorization: Bearer {{Authorization}}
Content-Type: application/json

### Update sharing session
PUT http://localhost:8080/sharing-sessions/b4b502a5-86d0-4e59-ba05-f588a0acb9e
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "sessionName": "Insurance application review2",
  "status": "ACCEPTED_STARTED",
  "initialShareMessage": "Please review the attached documents.",
  "description": "Document sharing session for project review.",
  "allowDocumentAddition": true,
  "allowDocumentDeletion": false,
  "allowDocumentDownload": true,
  "allowDocumentUpdate": true,
  "allowDocumentUpload": true
}

### Add sharing session document
POST http://localhost:8080/sharing-sessions/b4b502a5-86d0-4e59-ba05-f588aacb9e6/documents
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "title": "Project Plansy",
  "restrictedType": "PDF"
}


### Update sharing session document
PUT http://localhost:8080/sharing-sessions/b4b502a5-86d0-4e59-ba05-f588a0acb9e6/documents/b4cbefb4-3d94-4864-93b1-2f554b959cca
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "title": "asdasdasd",
  "restrictedType": "WORD"
}

### Delete sharing session document
DELETE http://localhost:8080/sharing-sessions/b4b502a5-86d0-4e59-ba05-f588a0acb9e6/documents/f48bf983-cc03-4c2f-b389-c748c664953c
Authorization: Bearer {{Authorization}}

### Get sharing session document audit logs
GET http://localhost:8080/sharing-sessions/b4b502a5-86d0-4e59-ba05-f588a0acb9e6/documents/b4cbefb4-3d94-4864-93b1-2f554b959cca/audit
Authorization: Bearer {{Authorization}}

### Upload sharing session document
POST http://localhost:8080/sharing-sessions/b4b502a5-86d0-4e59-ba05-f588a0acb9e6/documents/b4cbefb4-3d94-4864-93b1-2f554b959cca/file
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{Authorization}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="UserManual.pdf"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< C:\Users\Black\Downloads\UserManual.pdf
--WebAppBoundary
Content-Disposition: form-data; name="encryptionMode"
Content-Type: text/plain

INTERNAL
--WebAppBoundary
Content-Disposition: form-data; name="extension"
Content-Type: text/plain

.docx
--WebAppBoundary--

### Download sharing session document
GET http://localhost:8080/sharing-sessions/b4b502a5-86d0-4e59-ba05-f588a0acb9e6/documents/b4cbefb4-3d94-4864-93b1-2f554b959cca/file
Authorization: Bearer {{Authorization}}

### Download Preview PDF sharing session document
GET http://localhost:8080/sharing-sessions/b4b502a5-86d0-4e59-ba05-f588a0acb9e6/documents/b4cbefb4-3d94-4864-93b1-2f554b959cca/preview
Authorization: Bearer {{Authorization}}