import {makeStyles, shorthands, tokens} from "@fluentui/react-components";

export const usePlatformContentStyles = makeStyles({
    container: {
        display: "flex",
        flexDirection: "column",
        width: "100%",
        height: "100%",
        minHeight: 0,
    },
    stickyBlock: {
        flexShrink: 0,
        backgroundColor: tokens.colorNeutralBackground1,
        paddingBottom: tokens.spacingVerticalS,
    },
    tabContent: {
        flex: 1,
        minHeight: 0,
        overflow: "hidden",
    },
    tabPanel: {
        display: "flex",
        flexDirection: "column",
        width: "100%",
        height: "100%",
        minHeight: 0,
    },
    actionToolbar: {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        flexWrap: "wrap",
        flexShrink: 0,
        paddingBottom: tokens.spacingVerticalS,
        ...shorthands.gap(tokens.spacingHorizontalM),
    },
    splitToolbar: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        flexWrap: "wrap",
        flexShrink: 0,
        paddingBottom: tokens.spacingVerticalS,
        ...shorthands.gap(tokens.spacingHorizontalM),
    },
    scrollableContent: {
        display: "flex",
        flexDirection: "column",
        flex: 1,
        minHeight: 0,
        overflowY: "auto",
        overflowX: "hidden",
        overscrollBehavior: "contain",
        boxSizing: "border-box",
        paddingInline: tokens.spacingHorizontalS,
        ...shorthands.gap(tokens.spacingVerticalM),
    },
    grid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 18rem), 1fr))",
        ...shorthands.gap(tokens.spacingHorizontalM),
    },
    card: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        minWidth: 0,
        ...shorthands.border("1px", "solid", tokens.colorNeutralStroke2),
        ...shorthands.borderRadius(tokens.borderRadiusMedium),
        ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalM),
        ...shorthands.gap(tokens.spacingVerticalM),
    },
    blueprintCard: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        minWidth: 0,
        ...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
        ...shorthands.borderRadius(tokens.borderRadiusXLarge),
        ...shorthands.padding(tokens.spacingVerticalM, tokens.spacingHorizontalL),
        ...shorthands.gap(tokens.spacingHorizontalS),
    },
    blueprintCardContent: {
        display: "flex",
        flexDirection: "column",
        flex: 1,
        minWidth: 0,
        ...shorthands.gap(tokens.spacingHorizontalXS),
    },
    summaryText: {
        color: tokens.colorNeutralForeground2,
    },
    badgeRow: {
        display: "flex",
        flexWrap: "wrap",
        alignItems: "center",
        ...shorthands.gap(tokens.spacingHorizontalSNudge),
    },
    cardBody: {
        display: "flex",
        flexDirection: "column",
        ...shorthands.gap(tokens.spacingVerticalXS),
    },
    badges: {
        display: "flex",
        flexWrap: "wrap",
        ...shorthands.gap(tokens.spacingHorizontalXS),
    },
    actions: {
        display: "flex",
        flexWrap: "wrap",
        justifyContent: "flex-end",
        ...shorthands.gap(tokens.spacingHorizontalXS),
    },
    loading: {
        display: "flex",
        justifyContent: "center",
        ...shorthands.padding(tokens.spacingVerticalXL),
    },
});
