import {makeStyles, tokens} from "@fluentui/react-components";

export const useHelpDocumentationSidebarStyles = makeStyles({
    spacer: {
        flexShrink: 0,
        height: "100%",
        width: "var(--help-doc-panel-width, 400px)",
    },
    panel: {
        position: "fixed",
        top: "0",
        right: "0",
        width: "var(--help-doc-panel-width, 400px)",
        height: "100vh",
        zIndex: 1000010,
        backgroundColor: tokens.colorNeutralBackground1,
        borderLeft: `1px solid ${tokens.colorNeutralStroke2}`,
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
    },
    resizeHandle: {
        position: "absolute",
        left: 0,
        top: 0,
        bottom: 0,
        width: "16px",
        cursor: "col-resize",
        zIndex: 2,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        ":hover > span": {
            color: tokens.colorBrandForeground1,
            backgroundColor: tokens.colorNeutralBackground1Hover,
        },
    },
    resizeGrip: {
        position: "absolute",
        top: "50%",
        left: "50%",
        transform: "translate(-50%, -50%)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: "16px",
        height: "32px",
        borderRadius: tokens.borderRadiusMedium,
        backgroundColor: tokens.colorNeutralBackground3,
        border: `1px solid ${tokens.colorNeutralStroke2}`,
        color: tokens.colorNeutralForeground3,
        cursor: "col-resize",
        pointerEvents: "none",
        transition: "color 0.15s, background-color 0.15s",
        boxShadow: tokens.shadow2,
    },
    header: {
        position: "sticky",
        top: 0,
        zIndex: 1,
        backgroundColor: tokens.colorNeutralBackground1,
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalL}`,
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingHorizontalS,
    },
    breadcrumbRow: {
        display: "flex",
        flexWrap: "wrap",
        gap: tokens.spacingHorizontalSNudge,
        color: tokens.colorNeutralForeground3,
    },
    crumbSeparator: {
        color: tokens.colorNeutralForeground4,
    },
    titleRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: tokens.spacingHorizontalS,
    },
    titleText: {
        fontWeight: tokens.fontWeightSemibold,
        flex: 1,
        minWidth: 0,
    },
    headerActions: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXXS,
        flexShrink: 0,
    },
    content: {
        flex: 1,
        overflowY: "auto",
        padding: tokens.spacingHorizontalXXXL,
        color: tokens.colorNeutralForeground2,
        lineHeight: tokens.lineHeightBase300,
        fontSize: tokens.fontSizeBase300,
        "& p": {
            margin: `0 0 ${tokens.spacingVerticalM}`,
        },
        "& ul, & ol": {
            margin: `0 0 ${tokens.spacingVerticalM}`,
            paddingLeft: tokens.spacingHorizontalL,
        },
        "& li": {
            marginBottom: tokens.spacingVerticalSNudge,
        },
        "& a[data-help-article]": {
            color: tokens.colorBrandForeground1,
            textDecorationLine: "underline",
            cursor: "pointer",
        },
    },
    nav: {
        flex: 1,
        overflowY: "auto",
        display: "flex",
        flexDirection: "column",
    },
    navArticleItem: {
        display: "block",
        width: "100%",
        textAlign: "left",
        padding: `${tokens.spacingVerticalSNudge} ${tokens.spacingHorizontalL} ${tokens.spacingVerticalSNudge} ${tokens.spacingHorizontalXXXL}`,
        border: "none",
        background: "none",
        cursor: "pointer",
        color: tokens.colorNeutralForeground2,
        lineHeight: tokens.lineHeightBase300,
        ":hover": {
            backgroundColor: tokens.colorNeutralBackground1Hover,
            color: tokens.colorNeutralForeground1,
        },
    },
    navArticleItemActive: {
        color: tokens.colorBrandForeground1,
        fontWeight: tokens.fontWeightSemibold,
    },
    navArticleList: {
        display: "flex",
        flexDirection: "column",
        paddingBottom: tokens.spacingVerticalXS,
    },
    searchContainer: {
        padding: `${tokens.spacingVerticalMNudge} ${tokens.spacingHorizontalL}`,
        borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
        flexShrink: 0,
    },
    searchInput: {
        width: "100%",
    },
    searchResultTitle: {
        display: "block",
        fontSize: tokens.fontSizeBase300,
    },
    searchResultSection: {
        display: "block",
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground4,
        marginTop: tokens.spacingVerticalXXS,
    },
    searchNoResults: {
        display: "block",
        padding: tokens.spacingHorizontalL,
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase300,
        textAlign: "center",
    },
});
